export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_CATEGORY_PRODUCTS = 'SET_CATEGORY_PRODUCTS';
export const SET_COLLECTIONS = 'SET_COLLECTIONS';
export const SET_LINK_PATH = 'SET_LINK_PATH';